---
- name: provisioning 
  hosts: localhost
  connection: local 
  roles:
    - provisioning

- name: configuring
  hosts: launched
  remote_user: ec2-user
  become: yes
  become_method: sudo
  roles:
    - configure


- name: cleaning
  hosts: localhost
  connection: local
  roles:
      - clean
