- name: remove host entry of provisioned ec2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: remove the entries of ec2 vm in ansible host file
    lineinfile:
        path: hosts
        regexp: "ansible_ssh_user=ec2-user"
        state: absent
