- name: make hostentries for all the provisioned vms
  hosts: launched
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: true
  tasks: 
  - name: Install httpd on provisioned instance
    yum: 
     name: httpd
     state: present
     

  - name: Start httpd service
    service: 
      name: httpd
      state: started
