---



- name: Launch new VM
  ec2:
    keypair: "{{ ec2_keypair }}"
    type: "{{ ec2_instance_type }}"
    image: "{{ item.image }}"
    group: "{{ item.group }}"
    region: "{{ ec2_region }}"
    instance_tags: "{'ansible_group':'newvm', 'type':'{{ ec2_instance_type }}', 'group':'{{ item.group }}'}"
    count: "{{ ec2_instance_count }}"
    wait: true
  register: newvm
  with_items:
     - { image: ami-0b500ef59d8335eee , group: Jenkins }
- debug:
   var: newvm

- name: Add new VM public IP to hosts file
  lineinfile:
          dest: hosts
          regexp: "{{ item['instances'][0]['public_ip'] }}"
          insertafter: "[launched]"
          line: "{{ item['instances'][0]['public_ip'] }} ansible_ssh_private_key_file=~/.ssh/{{ ec2_keypair }}.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
  with_items:
        - "{{ newvm.results }}"

- name: Wait for SSH to come up
  local_action: wait_for host="{{ item['instances'][0]['public_ip'] }}" port=22 delay=60 timeout=320 state=started
  with_items:
         - "{{ newvm.results }}"

